# Database Password Rotation (every 90 days)
apiVersion: cloudscheduler.cnrm.cloud.google.com/v1beta1
kind: CloudSchedulerJob
metadata:
  name: database-password-rotation
  namespace: default
spec:
  name: database-password-rotation
  description: "Rotate database password every 90 days"
  schedule: "0 3 1 */3 *"  # 3 AM on the 1st of every 3rd month
  timeZone: "UTC"
  httpTarget:
    uri: "https://REGION-PROJECT_ID.cloudfunctions.net/rotate-secret"
    httpMethod: "POST"
    headers:
      Content-Type: "application/json"
    body: |
      {
        "secret_id": "database-password",
        "environment": "prod",
        "rotation_type": "password"
      }
  retryConfig:
    retryCount: 3
    maxRetryDuration: "300s"
    minBackoffDuration: "5s"
    maxBackoffDuration: "60s"
    maxDoublings: 5
