# JWT Secret Key Rotation (every 30 days)
apiVersion: cloudscheduler.cnrm.cloud.google.com/v1beta1
kind: CloudSchedulerJob
metadata:
  name: jwt-secret-rotation
  namespace: default
spec:
  name: jwt-secret-rotation
  description: "Rotate JWT secret key every 30 days"
  schedule: "0 2 1 * *"  # 2 AM on the 1st of every month
  timeZone: "UTC"
  httpTarget:
    uri: "https://REGION-PROJECT_ID.cloudfunctions.net/rotate-secret"
    httpMethod: "POST"
    headers:
      Content-Type: "application/json"
    body: |
      {
        "secret_id": "jwt-secret-key",
        "environment": "prod",
        "rotation_type": "jwt"
      }
  retryConfig:
    retryCount: 3
    maxRetryDuration: "300s"
    minBackoffDuration: "5s"
    maxBackoffDuration: "60s"
    maxDoublings: 5
