# Redis Password Rotation (every 60 days)
apiVersion: cloudscheduler.cnrm.cloud.google.com/v1beta1
kind: CloudSchedulerJob
metadata:
  name: redis-password-rotation
  namespace: default
spec:
  name: redis-password-rotation
  description: "Rotate Redis password every 60 days"
  schedule: "0 4 1 */2 *"  # 4 AM on the 1st of every 2nd month
  timeZone: "UTC"
  httpTarget:
    uri: "https://REGION-PROJECT_ID.cloudfunctions.net/rotate-secret"
    httpMethod: "POST"
    headers:
      Content-Type: "application/json"
    body: |
      {
        "secret_id": "redis-password",
        "environment": "prod",
        "rotation_type": "password"
      }
  retryConfig:
    retryCount: 3
    maxRetryDuration: "300s"
    minBackoffDuration: "5s"
    maxBackoffDuration: "60s"
    maxDoublings: 5
