# Secret Validation (daily)
apiVersion: cloudscheduler.cnrm.cloud.google.com/v1beta1
kind: CloudSchedulerJob
metadata:
  name: secret-validation
  namespace: default
spec:
  name: secret-validation
  description: "Validate all secrets are accessible daily"
  schedule: "0 6 * * *"  # 6 AM every day
  timeZone: "UTC"
  httpTarget:
    uri: "https://REGION-PROJECT_ID.cloudfunctions.net/validate-secrets"
    httpMethod: "POST"
    headers:
      Content-Type: "application/json"
    body: |
      {
        "environment": "prod"
      }
  retryConfig:
    retryCount: 2
    maxRetryDuration: "180s"
    minBackoffDuration: "10s"
    maxBackoffDuration: "30s"
    maxDoublings: 3
