version: '3.8'

services:
  # Kafka Broker (KRaft mode - no Zookeeper needed)
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    hostname: kafka
    container_name: devcycle-kafka
    ports:
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_LOG_RETENTION_HOURS: 168
      KAFKA_LOG_SEGMENT_BYTES: 1073741824
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 300000
      KAFKA_LOG_DIRS: '/var/lib/kafka/data'
      KAFKA_CONTROLLER_LOG_DIRS: '/var/lib/kafka/data'
    volumes:
      - kafka-data:/var/lib/kafka/data
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server localhost:9092 --list"]
      interval: 30s
      timeout: 10s
      retries: 5

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: devcycle-postgres
    restart: unless-stopped
    ports:
      - "${DOCKER_POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_DB: ${DOCKER_POSTGRES_DB:-devcycle}
      POSTGRES_USER: ${DOCKER_POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${DOCKER_POSTGRES_PASSWORD:-devcycle123}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DOCKER_POSTGRES_USER:-postgres} -d ${DOCKER_POSTGRES_DB:-devcycle}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - default

  # Redis Cache (for session management and token blacklisting)
  redis:
    image: redis:7-alpine
    container_name: devcycle-redis
    restart: unless-stopped
    ports:
      - "${DOCKER_REDIS_PORT:-6379}:6379"
    environment:
      REDIS_PASSWORD: ${DOCKER_REDIS_PASSWORD:-}
    command: >
      sh -c "
        if [ -n \"$$REDIS_PASSWORD\" ]; then
          redis-server --requirepass $$REDIS_PASSWORD --appendonly yes
        else
          redis-server --appendonly yes
        fi
      "
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - default

  # DevCycle Application with Auto-Migration
  app:
    image: python:3.12-slim
    container_name: devcycle-app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - ENVIRONMENT=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=devcycle123
      - DB_DATABASE=devcycle
    volumes:
      - .:/app
    working_dir: /app
    command: >
      bash -c "
        apt-get update && apt-get install -y postgresql-client &&
        pip install poetry &&
        poetry config virtualenvs.create false &&
        poetry install --only=main &&
        echo 'Waiting for database...' &&
        while ! pg_isready -h postgres -p 5432 -U postgres; do sleep 1; done &&
        echo 'Database ready, running migrations...' &&
        poetry run aerich upgrade &&
        echo 'Starting application...' &&
        poetry run uvicorn devcycle.api.app:app --host 0.0.0.0 --port 8000 --reload
      "
    ports:
      - "8000:8000"
    restart: unless-stopped

volumes:
  kafka-data:
    driver: local
  postgres-data:
    driver: local
  redis-data:
    driver: local

networks:
  default:
    name: devcycle-network
